services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    environment:
      DNS1: "1.0.0.1"
      DNS2: "1.1.1.1"
    ports:
    # change the <ip> to public ip of this machine if 127.0.0.1:53 is not bindable
      - <ip>:53:53/udp
      - <ip>:53:53/tcp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./common/dnsmasq.conf:/etc/dnsmasq.conf
    restart: always