from enum import Enum


class ResponseName(Enum):
    SUCCESS = 0
    SECRET_KEY_INVALID = 1
    SERVICE_DISABLED = 2
    DATABASE_UNAVAILABLE = 3
    LOGIN_TICKET_INVALID = 4
    LOGIN_TICKET_EXPIRED = 5
    TABLE_NOT_FOUND = 6
    RECORD_NOT_FOUND = 7
    FIELD_NOT_FOUND = 8
    FIELD_TYPE_INVALID = 9
    NO_PERMISSION = 10
    RECORD_LIMIT_REACHED = 11
    NOT_RATABLE = 12
    NOT_OWNED = 13
    FILTER_INVALID = 14
    SORT_INVALID = 15
    TARGET_FILTER_INVALID = 16
    CERTIFICATE_INVALID = 17
    ALREADY_REPORTED = 18
    RECORD_LOCKED = 19
    CONSTRUCTOR_ERROR = 20
    ERROR_CREATING_REQUEST = 21
    ERROR_SENDING_REQUEST = 22
    HTTP_ERROR = 23
    RESPONSE_PARSE_ERROR = 24
    NO_FILE_DATA_ERROR = 25
    ERROR = 26


class SakePlatform(Enum):
    """
    determine different platform
    """
    Windows = "WINDOWS"
    Unity = "UNITY"
