from enum import IntEnum


class LoginRequestType(IntEnum):
    UNIQUE_NICK_LOGIN = 1
    NICK_AND_EMAIL_LOGIN = 2


class WhoRequestType(IntEnum):
    GET_CHANNEL_USER_INFO = 0
    GET_USER_INFO = 1


class MessageType(IntEnum):
    CHANNEL_MESSAGE = 0
    USER_MESSAGE = 1


class GetKeyRequestType(IntEnum):
    GET_CHANNEL_ALL_USER_KEY_VALUE = 0
    GET_CHANNEL_SPECIFIC_USER_KEY_VALUE = 1


class ModeOperationType(IntEnum):
    ENABLE_USER_QUIET_FLAG = 0
    DISABLE_USER_QUIET_FLAG = 1
    ADD_CHANNEL_PASSWORD = 2
    REMOVE_CHANNEL_PASSWORD = 3
    ADD_CHANNEL_USER_LIMITS = 4
    REMOVE_CHANNEL_USER_LIMITS = 5
    ADD_BAN_ON_USER = 6
    GET_BANNED_USERS = 7
    REMOVE_BAN_ON_USER = 8
    ADD_CHANNEL_OPERATOR = 9
    REMOVE_CHANNEL_OPERATOR = 10
    ENABLE_USER_VOICE_PERMISSION = 11
    DISABLE_USER_VOICE_PERMISSION = 12
    SET_INVITED_ONLY = 13
    REMOVE_INVITED_ONLY = 14
    SET_PRIVATE_CHANNEL_FLAG = 15
    REMOVE_PRIVATE_CHANNEL_FLAG = 16
    SET_SECRET_CHANNEL_FLAG = 17
    REMOVE_SECRET_CHANNEL_FLAG = 18
    SET_MODERATED_CHANNEL_FLAG = 19
    REMOVE_MODERATED_CHANNEL_FLAG = 20
    ENABLE_EXTERNAL_MESSAGES_FLAG = 21
    DISABLE_EXTERNAL_MESSAGES_FLAG = 22
    SET_TOPIC_CHANGE_BY_OPERATOR_FLAG = 23
    REMOVE_TOPIC_CHANGE_BY_OPERATOR_FLAG = 24
    SET_OPERATOR_ABEY_CHANNEL_LIMITS = 25
    REMOVE_OPERATOR_ABEY_CHANNEL_LIMITS = 26


class ModeRequestType(IntEnum):
    GET_CHANNEL_MODES = 0
    GET_CHANNEL_AND_USER_MODES = 1
    SET_CHANNEL_MODES = 2


class TopicRequestType(IntEnum):
    GET_CHANNEL_TOPIC = 0
    SET_CHANNEL_TOPIC = 1
