from enum import Enum


class IRCErrorCode(Enum):
    NO_SUCH_NICK = "401"
    NO_SUCH_CHANNEL = "403"
    TOO_MANY_CHANNELS = "405"
    ERR_ONE_US_NICK_NAME = "432"
    NICK_NAME_IN_USE = "433"
    MORE_PARAMETERS = "461"
    CHANNEL_IS_FULL = "471"
    INVITE_ONLY_CHAN = "473"
    BANNED_FROM_CHAN = "474"
    BAD_CHANNEL_KEY = "475"
    BAD_CHAN_MASK = "476"
    LOGIN_FAILED = "708"
    NO_UNIQUE_NICK = "709"
    UNIQUE_NICK_EXPIRED = "710"
    REGISTER_NICK_FAILED = "711"
