//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DatabaseModel.SQLite
{
	/// <summary>
	/// Database       : RetroSpy
	/// Data Source    : RetroSpy
	/// Server Version : 3.24.0
	/// </summary>
	public partial class RetroSpyDB : LinqToDB.Data.DataConnection
	{
		public ITable<@namespace> Namespaces  { get { return this.GetTable<@namespace>(); } }
		public ITable<Addrequest> Addrequests { get { return this.GetTable<Addrequest>(); } }
		public ITable<Blocked>    Blockeds    { get { return this.GetTable<Blocked>(); } }
		public ITable<Buddystatu> Buddystatus { get { return this.GetTable<Buddystatu>(); } }
		public ITable<Friend>     Friends     { get { return this.GetTable<Friend>(); } }
		public ITable<Game>       Games       { get { return this.GetTable<Game>(); } }
		public ITable<Grouplist>  Grouplists  { get { return this.GetTable<Grouplist>(); } }
		public ITable<Message>    Messages    { get { return this.GetTable<Message>(); } }
		public ITable<Partner>    Partners    { get { return this.GetTable<Partner>(); } }
		public ITable<Profile>    Profiles    { get { return this.GetTable<Profile>(); } }
		public ITable<User>       Users       { get { return this.GetTable<User>(); } }

		public RetroSpyDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public RetroSpyDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("namespace")]
	public partial class @namespace
	{
		[Column("id"),          NotNull    ] public long   Id          { get; set; } // integer
		[Column("profileid"),   NotNull    ] public long   Profileid   { get; set; } // integer
		[Column("uniquenick"),  NotNull    ] public string Uniquenick  { get; set; } // text(max)
		[Column("namespaceid"), NotNull    ] public long   Namespaceid { get; set; } // integer
		[Column("partnerid"),   NotNull    ] public string Partnerid   { get; set; } // text(max)
		[Column("productid"),   NotNull    ] public long   Productid   { get; set; } // integer
		[Column("gamename"),    NotNull    ] public string Gamename    { get; set; } // text(max)
		[Column("cdkeyenc"),    NotNull    ] public string Cdkeyenc    { get; set; } // text(max)
		[Column("sesskey"),        Nullable] public long?  Sesskey     { get; set; } // integer
		[Column("firewall"),    NotNull    ] public string Firewall    { get; set; } // text(max)
		[Column("port"),        NotNull    ] public long   Port        { get; set; } // integer
		[Column("authtoken"),      Nullable] public string Authtoken   { get; set; } // text(max)
	}

	[Table("addrequests")]
	public partial class Addrequest
	{
		[Column("id"),            Nullable] public object Id            { get; set; }
		[Column("profileid"),     Nullable] public object Profileid     { get; set; }
		[Column("targetid"),      Nullable] public object Targetid      { get; set; }
		[Column("namespaceid"),   Nullable] public object Namespaceid   { get; set; }
		[Column("reason"),        Nullable] public object Reason        { get; set; }
		[Column("syncrequested"), Nullable] public object Syncrequested { get; set; }
	}

	[Table("blocked")]
	public partial class Blocked
	{
		[Column("id"),          Nullable] public object Id          { get; set; }
		[Column("profileid"),   Nullable] public object Profileid   { get; set; }
		[Column("targetid"),    Nullable] public object Targetid    { get; set; }
		[Column("namespaceid"), Nullable] public object Namespaceid { get; set; }
	}

	[Table("buddystatus")]
	public partial class Buddystatu
	{
		[Column("profileid"),      Nullable] public object Profileid      { get; set; }
		[Column("namespaceid"),    Nullable] public object Namespaceid    { get; set; }
		[Column("profile"),        Nullable] public object Profile        { get; set; }
		[Column("statusstate"),    Nullable] public object Statusstate    { get; set; }
		[Column("buddyip"),        Nullable] public object Buddyip        { get; set; }
		[Column("hostip"),         Nullable] public object Hostip         { get; set; }
		[Column("hostprivateip"),  Nullable] public object Hostprivateip  { get; set; }
		[Column("queryreport"),    Nullable] public object Queryreport    { get; set; }
		[Column("hostport"),       Nullable] public object Hostport       { get; set; }
		[Column("sessionflags"),   Nullable] public object Sessionflags   { get; set; }
		[Column("richstatus"),     Nullable] public object Richstatus     { get; set; }
		[Column("gametype"),       Nullable] public object Gametype       { get; set; }
		[Column("gamevariant"),    Nullable] public object Gamevariant    { get; set; }
		[Column("gamemapname"),    Nullable] public object Gamemapname    { get; set; }
		[Column("productid"),      Nullable] public object Productid      { get; set; }
		[Column("quietmodefalgs"), Nullable] public object Quietmodefalgs { get; set; }
	}

	[Table("friends")]
	public partial class Friend
	{
		[Column("id"),          Nullable] public object Id          { get; set; }
		[Column("profileid"),   Nullable] public object Profileid   { get; set; }
		[Column("targetid"),    Nullable] public object Targetid    { get; set; }
		[Column("namespaceid"), Nullable] public object Namespaceid { get; set; }
	}

	[Table("games")]
	public partial class Game
	{
		[Column("id"),               Nullable] public object Id               { get; set; }
		[Column("gamename"),         Nullable] public object Gamename         { get; set; }
		[Column("secretkey"),        Nullable] public object Secretkey        { get; set; }
		[Column("description"),      Nullable] public object Description      { get; set; }
		[Column("queryport"),        Nullable] public object Queryport        { get; set; }
		[Column("backendflags"),     Nullable] public object Backendflags     { get; set; }
		[Column("disabledservices"), Nullable] public object Disabledservices { get; set; }
		[Column("keylist"),          Nullable] public object Keylist          { get; set; }
		[Column("keytypelist"),      Nullable] public object Keytypelist      { get; set; }
	}

	[Table("grouplist")]
	public partial class Grouplist
	{
		[Column("gameid"),     Nullable] public object Gameid     { get; set; }
		[Column("groupid"),    Nullable] public object Groupid    { get; set; }
		[Column("maxwaiting"), Nullable] public object Maxwaiting { get; set; }
		[Column("name"),       Nullable] public object Name       { get; set; }
		[Column("numplayers"), Nullable] public object Numplayers { get; set; }
		[Column("numservers"), Nullable] public object Numservers { get; set; }
		[Column("numwaiting"), Nullable] public object Numwaiting { get; set; }
		[Column("other"),      Nullable] public object Other      { get; set; }
		[Column("password"),   Nullable] public object Password   { get; set; }
		[Column("updatetime"), Nullable] public object Updatetime { get; set; }
	}

	[Table("messages")]
	public partial class Message
	{
		[Column("id"),          Nullable] public object Id            { get; set; }
		[Column("from"),        Nullable] public object From          { get; set; }
		[Column("to"),          Nullable] public object To            { get; set; }
		[Column("date"),        Nullable] public object Date          { get; set; }
		[Column("message"),     Nullable] public object MessageColumn { get; set; }
		[Column("namespaceid"), Nullable] public object Namespaceid   { get; set; }
	}

	[Table("partners")]
	public partial class Partner
	{
		[Column("id"),        PrimaryKey, Identity] public long   Id        { get; set; } // integer
		[Column("partnerid"), NotNull             ] public long   Partnerid { get; set; } // integer
		[Column("name"),      NotNull             ] public string Name      { get; set; } // text(max)
	}

	[Table("profiles")]
	public partial class Profile
	{
		[Column("profileid"),        NotNull] public long    Profileid        { get; set; } // integer
		[Column("userid"),           NotNull] public long    Userid           { get; set; } // integer
		[Column("nick"),             NotNull] public string  Nick             { get; set; } // text(max)
		[Column("status"),           NotNull] public string  Status           { get; set; } // text(max)
		[Column("statstring"),       NotNull] public string  Statstring       { get; set; } // text(max)
		[Column("firstname"),        NotNull] public string  Firstname        { get; set; } // text(max)
		[Column("lastname"),         NotNull] public string  Lastname         { get; set; } // text(max)
		[Column("publicmask"),       NotNull] public long    Publicmask       { get; set; } // integer
		[Column("latitude"),         NotNull] public decimal Latitude         { get; set; } // numeric
		[Column("longitude"),        NotNull] public decimal Longitude        { get; set; } // numeric
		[Column("aim"),              NotNull] public string  Aim              { get; set; } // text(max)
		[Column("picture"),          NotNull] public long    Picture          { get; set; } // integer
		[Column("occupationid"),     NotNull] public long    Occupationid     { get; set; } // integer
		[Column("incomeid"),         NotNull] public long    Incomeid         { get; set; } // integer
		[Column("industryid"),       NotNull] public long    Industryid       { get; set; } // integer
		[Column("marriedid"),        NotNull] public long    Marriedid        { get; set; } // integer
		[Column("childcount"),       NotNull] public long    Childcount       { get; set; } // integer
		[Column("interests1"),       NotNull] public long    Interests1       { get; set; } // integer
		[Column("ownership1"),       NotNull] public long    Ownership1       { get; set; } // integer
		[Column("connectiontype"),   NotNull] public long    Connectiontype   { get; set; } // integer
		[Column("sex"),              NotNull] public long    Sex              { get; set; } // integer
		[Column("zipcode"),          NotNull] public string  Zipcode          { get; set; } // text(max)
		[Column("countrycode"),      NotNull] public string  Countrycode      { get; set; } // text(max)
		[Column("homepage"),         NotNull] public string  Homepage         { get; set; } // text(max)
		[Column("birthday"),         NotNull] public long    Birthday         { get; set; } // integer
		[Column("birthmonth"),       NotNull] public long    Birthmonth       { get; set; } // integer
		[Column("birthyear"),        NotNull] public long    Birthyear        { get; set; } // integer
		[Column("location"),         NotNull] public string  Location         { get; set; } // text(max)
		[Column("icquin"),           NotNull] public long    Icquin           { get; set; } // integer
		[Column("quietflags"),       NotNull] public long    Quietflags       { get; set; } // integer
		[Column("streetaddr"),       NotNull] public string  Streetaddr       { get; set; } // text(max)
		[Column("city"),             NotNull] public string  City             { get; set; } // text(max)
		[Column("cpubrandid"),       NotNull] public string  Cpubrandid       { get; set; } // text(max)
		[Column("cpuspeed"),         NotNull] public string  Cpuspeed         { get; set; } // text(max)
		[Column("memory"),           NotNull] public string  Memory           { get; set; } // text(max)
		[Column("videocard1string"), NotNull] public string  Videocard1string { get; set; } // text(max)
		[Column("videocard1ram"),    NotNull] public string  Videocard1ram    { get; set; } // text(max)
		[Column("videocard2string"), NotNull] public string  Videocard2string { get; set; } // text(max)
		[Column("videocard2ram"),    NotNull] public string  Videocard2ram    { get; set; } // text(max)
		[Column("subscription"),     NotNull] public string  Subscription     { get; set; } // text(max)
		[Column("adminrights"),      NotNull] public string  Adminrights      { get; set; } // text(max)
	}

	[Table("users")]
	public partial class User
	{
		[Column("userid"),        NotNull] public long   Userid        { get; set; } // integer
		[Column("email"),         NotNull] public string Email         { get; set; } // text(max)
		[Column("password"),      NotNull] public string Password      { get; set; } // text(max)
		[Column("emailverified"), NotNull] public long   Emailverified { get; set; } // integer
		[Column("createddate"),   NotNull] public string Createddate   { get; set; } // text(max)
		[Column("useddate"),      NotNull] public string Useddate      { get; set; } // text(max)
		[Column("deleted"),       NotNull] public long   Deleted       { get; set; } // integer
		[Column("banned"),        NotNull] public long   Banned        { get; set; } // integer
		[Column("lastip"),        NotNull] public string Lastip        { get; set; } // text(max)
		[Column("lastonline"),    NotNull] public string Lastonline    { get; set; } // text(max)
	}

	public static partial class TableExtensions
	{
		public static Partner Find(this ITable<Partner> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
